<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LifeFlow.Application\LifeFlow.Application.csproj" />
    <ProjectReference Include="..\LifeFlow.Domain\LifeFlow.Domain.csproj" />
    <ProjectReference Include="..\LifeFlow.Infrastructure\LifeFlow.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
  </ItemGroup>

</Project>
